"use client";

import { FormEvent, useEffect, useRef, useState } from "react";

type Page = "home" | "search" | "product" | "free" | "pricing" | "cart" | "assets";
type UserMode = "guest" | "basic" | "pro" | "max";
type AccountTab = "My Assets" | "Plan & Unlocks" | "My Orders" | "Favorites" | "Account Settings";
type ModelType = "SketchUp" | "3ds Max";
type Model = { id: number; title: string; type: ModelType; category: string; image: string; checked: boolean; free?: boolean; version?: string; renderer?: string; size: string };

const models: Model[] = [
  { id: 1, title: "Lunaro Modular Sofa", type: "3ds Max", category: "Sofas", image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=88", checked: true, version: "2021", renderer: "Corona", size: "286 MB" },
  { id: 2, title: "Noma Lounge Chair", type: "SketchUp", category: "Chairs", image: "https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?auto=format&fit=crop&w=1200&q=88", checked: true, version: "2020", size: "42 MB" },
  { id: 3, title: "Aster Pendant Light", type: "3ds Max", category: "Lighting", image: "https://images.unsplash.com/photo-1540932239986-30128078f3c5?auto=format&fit=crop&w=1200&q=88", checked: true, version: "2022", renderer: "V-Ray", size: "68 MB" },
  { id: 4, title: "Olive Tree No. 08", type: "3ds Max", category: "Plants", image: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=1200&q=88", checked: true, version: "2020", renderer: "Corona", size: "214 MB" },
  { id: 5, title: "Courtyard House 27", type: "SketchUp", category: "Architecture", image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=88", checked: true, version: "2021", size: "119 MB" },
  { id: 6, title: "Solace Dining Collection", type: "3ds Max", category: "Dining", image: "https://images.unsplash.com/photo-1617806118233-18e1de247200?auto=format&fit=crop&w=1200&q=88", checked: true, free: true, version: "2021", renderer: "Corona", size: "175 MB" },
  { id: 7, title: "Kanso Platform Bed", type: "SketchUp", category: "Beds", image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=88", checked: true, free: true, version: "2019", size: "34 MB" },
  { id: 8, title: "Milo Travertine Table", type: "3ds Max", category: "Tables", image: "https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?auto=format&fit=crop&w=1200&q=88", checked: false, version: "2020", renderer: "V-Ray", size: "96 MB" },
  { id: 9, title: "Minimal Kitchen System", type: "SketchUp", category: "Kitchens", image: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=88", checked: true, free: true, version: "2021", size: "71 MB" },
  { id: 10, title: "Atelier Workspace Set", type: "3ds Max", category: "Office", image: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=88", checked: true, version: "2022", renderer: "Corona", size: "302 MB" },
  { id: 11, title: "Mediterranean Arch Set", type: "SketchUp", category: "Architecture", image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=88", checked: true, version: "2020", size: "88 MB" },
  { id: 12, title: "Botanical Planter Series", type: "3ds Max", category: "Plants", image: "https://images.unsplash.com/photo-1493552152660-f915ab47ae9d?auto=format&fit=crop&w=1200&q=88", checked: true, free: true, version: "2021", renderer: "Corona", size: "127 MB" },
];

const collections = [
  { title: "Warm Minimalism", count: 184, image: models[0].image }, { title: "Architectural Essentials", count: 96, image: models[4].image },
  { title: "Quiet Workspaces", count: 132, image: models[9].image }, { title: "Natural Living", count: 208, image: models[3].image },
];

const qualityCheckedModels = models.filter(model => model.checked);
const todayFreeModels: Model[] = Array.from({ length: 40 }, (_, index) => ({
  ...qualityCheckedModels[index % qualityCheckedModels.length],
  id: 100 + index,
  free: true,
  type: index < 20 ? "SketchUp" : "3ds Max",
  title: `${models[index % models.length].title} ${String(index + 1).padStart(2, "0")}`,
}));
const catalog = [...models, ...todayFreeModels];

function Icon({ name, size = 20 }: { name: "search" | "image" | "heart" | "cart" | "user" | "check" | "download" | "arrow" | "grid" | "filter" | "close" | "menu"; size?: number }) {
  const paths: Record<string, React.ReactNode> = {
    search: <><circle cx="11" cy="11" r="6.5"/><path d="m16 16 4.2 4.2"/></>, image: <><rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="9" cy="10" r="2"/><path d="m4 18 5-5 4 4 3-3 5 5"/></>,
    heart: <path d="M20.8 5.8a5.5 5.5 0 0 0-7.8 0L12 6.9l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 22l8.8-8.4a5.5 5.5 0 0 0 0-7.8Z"/>, cart: <><path d="M3 4h2l2.2 11.2a2 2 0 0 0 2 1.6h7.7a2 2 0 0 0 2-1.6L20.3 8H6"/><circle cx="10" cy="20" r="1"/><circle cx="18" cy="20" r="1"/></>,
    user: <><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></>, check: <><path d="M12 2.5 20 6v6c0 5-3.4 8.2-8 9.5C7.4 20.2 4 17 4 12V6l8-3.5Z"/><path d="m8.5 12 2.2 2.2 4.8-5"/></>,
    download: <><path d="M12 3v12m0 0 5-5m-5 5-5-5"/><path d="M4 19v2h16v-2"/></>, arrow: <path d="M5 12h14m-5-5 5 5-5 5"/>,
    grid: <><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/></>, filter: <><path d="M4 7h16M7 12h10m-7 5h4"/><circle cx="8" cy="7" r="1.5"/><circle cx="15" cy="12" r="1.5"/><circle cx="12" cy="17" r="1.5"/></>,
    close: <path d="m6 6 12 12M18 6 6 18"/>, menu: <path d="M4 7h16M4 12h16M4 17h16"/>,
  };
  return <svg className="icon" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>;
}

export default function Prototype() {
  const [page, setPage] = useState<Page>("home"), [query, setQuery] = useState(""), [selected, setSelected] = useState(models[0]);
  const [favorites, setFavorites] = useState<number[]>([3]), [cart, setCart] = useState<number[]>([]), [owned, setOwned] = useState<number[]>([]);
  const [user, setUser] = useState<UserMode>("guest"), [modal, setModal] = useState<"none" | "auth" | "checkout" | "cartCheckout" | "success">("none");
  const [authIntent, setAuthIntent] = useState<"none" | "primary" | "favorite" | "cart" | "cartCheckout" | "plan">("none");
  const [mobileNav, setMobileNav] = useState(false), [freeClaimed, setFreeClaimed] = useState(0), [toast, setToast] = useState("");
  const [searchType, setSearchType] = useState("All software"), [accountTab, setAccountTab] = useState<AccountTab>("My Assets");
  const [pendingPlan, setPendingPlan] = useState<"pro" | "max" | null>(null), [successCount, setSuccessCount] = useState(1);
  const [searchHistory, setSearchHistory] = useState(["Modern sofa", "Kitchen island", "Olive tree"]);
  function navigate(next: Page) { setPage(next); setMobileNav(false); window.scrollTo({ top: 0, behavior: "smooth" }); }
  function rememberSearch(term: string) { setSearchHistory(items => [term, ...items.filter(item => item.toLowerCase() !== term.toLowerCase())].slice(0, 5)); }
  function search(event?: FormEvent) { event?.preventDefault(); const term = query.trim() || "modern sofa"; setQuery(term); rememberSearch(term); navigate("search"); }
  function searchFor(term: string, type = "All software") { setQuery(term); setSearchType(type); rememberSearch(term); navigate("search"); }
  function openModel(model: Model) { setSelected(model); navigate("product"); }
  function toggleFavorite(id: number) { if (user === "guest") { setSelected(catalog.find(item => item.id === id) || selected); setAuthIntent("favorite"); return setModal("auth"); } setFavorites(v => v.includes(id) ? v.filter(x => x !== id) : [...v, id]); }
  function addToCart(id: number) { const model = catalog.find(item => item.id === id); if (!model?.checked || model.free || owned.includes(id)) return setToast(model && !model.checked ? "This demo item is unavailable" : "This model is already available to you"); if (user === "guest") { setSelected(model); setAuthIntent("cart"); return setModal("auth"); } setCart(v => v.includes(id) ? v : [...v, id]); setToast("Added to cart"); setTimeout(() => setToast(""), 1800); }
  function primaryAction(model: Model) { setSelected(model); setSuccessCount(1); if (!model.checked) return setToast("This demo item is unavailable"); if (owned.includes(model.id)) return setModal("success"); if (user === "guest") { setAuthIntent("primary"); return setModal("auth"); } if (model.free) { if (freeClaimed >= 3) return setToast("Today’s free limit reached"); setOwned(v => [...v, model.id]); setFreeClaimed(v => v + 1); return setModal("success"); } if (user === "pro" || user === "max") { setOwned(v => [...v, model.id]); return setModal("success"); } setModal("checkout"); }
  function authenticate() { setUser("basic"); if (authIntent === "favorite") { setFavorites(v => v.includes(selected.id) ? v : [...v, selected.id]); setModal("none"); setToast("Saved to Favorites"); } else if (authIntent === "cart") { setCart(v => v.includes(selected.id) ? v : [...v, selected.id]); setModal("none"); setToast("Added to cart"); } else if (authIntent === "cartCheckout") setModal("cartCheckout"); else if (authIntent === "primary" && selected.free) { setOwned(v => v.includes(selected.id) ? v : [...v, selected.id]); setFreeClaimed(v => v + 1); setModal("success"); } else if (authIntent === "primary") setModal("checkout"); else if (authIntent === "plan" && pendingPlan) { setUser(pendingPlan); setModal("none"); setToast(`${pendingPlan === "max" ? "Max" : "Pro"} plan selected in demo`); setPendingPlan(null); } else { setModal("none"); setToast("Signed in successfully"); } setAuthIntent("none"); }
  function completePurchase(ids = [selected.id]) { setOwned(v => Array.from(new Set([...v, ...ids]))); setCart(v => v.filter(id => !ids.includes(id))); setSuccessCount(ids.length); setModal("success"); }
  function choosePlan(mode: "pro" | "max") { if (user === "guest") { setPendingPlan(mode); setAuthIntent("plan"); setModal("auth"); } else { setUser(mode); setToast(`${mode === "max" ? "Max" : "Pro"} plan selected in demo`); } }
  function openAccount(tab: AccountTab) { if (user === "guest") { setAuthIntent("none"); setModal("auth"); return; } setAccountTab(tab); navigate("assets"); }
  const cartModels = models.filter(model => cart.includes(model.id));
  return <div className="app-shell">
    <Header page={page} query={query} cartCount={cart.length} user={user} mobileNav={mobileNav} onMobileNav={setMobileNav} onQuery={setQuery} onSearch={search} onSearchFor={searchFor} onNavigate={navigate} onAccount={() => openAccount("My Assets")} onFavorites={() => openAccount("Favorites")}/>
    {page === "home" && <Home onSearch={search} onSearchFor={searchFor} query={query} searchHistory={searchHistory} onQuery={setQuery} onNavigate={navigate} onOpen={openModel} favorites={favorites} owned={owned} onFavorite={toggleFavorite} onCart={addToCart}/>}
    {page === "search" && <SearchResults query={query} onQuery={setQuery} onSearch={search} type={searchType} onType={setSearchType} onOpen={openModel} favorites={favorites} owned={owned} onFavorite={toggleFavorite} onCart={addToCart}/>}
    {page === "product" && <ProductDetail model={selected} owned={owned.includes(selected.id)} user={user} favorite={favorites.includes(selected.id)} onFavorite={() => toggleFavorite(selected.id)} onPrimary={() => primaryAction(selected)} onCart={() => addToCart(selected.id)} onOpen={openModel} onPricing={() => navigate("pricing")}/>}
    {page === "free" && <FreePage claimed={freeClaimed} owned={owned} onOpen={openModel} onClaim={primaryAction}/>}
    {page === "pricing" && <Pricing user={user} onChoose={choosePlan} onBrowse={() => searchFor("All models")}/>}
    {page === "cart" && <CartPage items={cartModels} user={user} onRemove={id => setCart(v => v.filter(x => x !== id))} onOpen={openModel} onCheckout={() => { if (!cartModels.length) return; if (user === "guest") { setAuthIntent("cartCheckout"); setModal("auth"); } else setModal("cartCheckout"); }}/>}
    {page === "assets" && <Assets
      tab={accountTab} onTab={setAccountTab}
      owned={catalog.filter(m => owned.includes(m.id))} favorites={models.filter(m => favorites.includes(m.id))}
      user={user} freeClaimed={freeClaimed} onOpen={openModel}
      onBrowse={() => navigate("search")} onPricing={() => navigate("pricing")}
      onDemoDownload={() => setToast("Prototype only — no file was downloaded")}
      onAccountNotice={message => { setToast(message); setTimeout(() => setToast(""), 1800); }}
    />}
    <Footer onNavigate={navigate} onAccount={openAccount}/><DemoControl user={user} onUser={setUser} onReset={() => { setUser("guest"); setOwned([]); setCart([]); setFavorites([3]); setFreeClaimed(0); setPendingPlan(null); navigate("home"); }}/>{toast && <div className="toast" role="status">{toast}</div>}
    {modal !== "none" && <Modal onClose={() => setModal("none")}>{modal === "auth" && <Auth onContinue={authenticate}/>} {modal === "checkout" && <Checkout models={[selected]} user={user} onPay={() => completePurchase()}/>} {modal === "cartCheckout" && <Checkout models={cartModels} user={user} onPay={() => completePurchase(cartModels.map(model => model.id))}/>} {modal === "success" && <Success model={selected} count={successCount} onClose={() => setModal("none")} onAssets={() => { setModal("none"); openAccount("My Assets"); }}/>}</Modal>}
  </div>;
}

function Header({ page, query, cartCount, user, mobileNav, onMobileNav, onQuery, onSearch, onSearchFor, onNavigate, onAccount, onFavorites }: { page: Page; query: string; cartCount: number; user: UserMode; mobileNav: boolean; onMobileNav: (v: boolean) => void; onQuery: (v: string) => void; onSearch: (e?: FormEvent) => void; onSearchFor: (term: string, type?: string) => void; onNavigate: (p: Page) => void; onAccount: () => void; onFavorites: () => void }) {
  const nav = [{ label: "SketchUp Models", action: () => onSearchFor("SketchUp models", "SketchUp") }, { label: "3ds Max Models", action: () => onSearchFor("3ds Max models", "3ds Max") }, { label: "Today’s Free", action: () => onNavigate("free") }, { label: "Pricing", action: () => onNavigate("pricing") }];
  const accountLabel = user === "guest" ? "Sign in" : user === "pro" ? "Pro account" : user === "max" ? "Max account" : "My account";
  return <><div className="utility"><span>Professional 3D assets for architecture & interiors</span><span>English · USD</span></div><header className="header"><button className="logo" onClick={() => onNavigate("home")}>ARCHZZ</button><nav className={mobileNav ? "nav open" : "nav"}>{nav.map(item => <button key={item.label} className={(item.label === "Today’s Free" && page === "free") || (item.label === "Pricing" && page === "pricing") ? "active" : ""} onClick={item.action}>{item.label}</button>)}</nav><div className="header-actions"><button className="icon-button search-trigger" onClick={() => onNavigate("search")}><Icon name="search"/><span>Search</span></button><button className="icon-button hide-mobile" onClick={onFavorites} aria-label="Favorites"><Icon name="heart"/></button><button className="icon-button count-wrap" onClick={() => onNavigate("cart")} aria-label="Cart"><Icon name="cart"/>{cartCount > 0 && <b>{cartCount}</b>}</button><button className="account-button" onClick={onAccount}><Icon name="user"/><span>{accountLabel}</span></button><button className="mobile-menu" onClick={() => onMobileNav(!mobileNav)}><Icon name={mobileNav ? "close" : "menu"}/></button></div></header>{page !== "home" && page !== "search" && <form className="compact-search" onSubmit={onSearch}><Icon name="search"/><input value={query} onChange={e => onQuery(e.target.value)} placeholder="Search 1M+ professional 3D models"/><button type="button" disabled title="Image search is not connected in this prototype" aria-label="Image search · Demo only"><Icon name="image"/></button><button className="small-search">Search</button></form>}</>;
}

function Home({ query, searchHistory, onQuery, onSearch, onSearchFor, onNavigate, onOpen, favorites, owned, onFavorite, onCart }: { query: string; searchHistory: string[]; onQuery: (v: string) => void; onSearch: (e?: FormEvent) => void; onSearchFor: (term: string, type?: string) => void; onNavigate: (p: Page) => void; onOpen: (m: Model) => void; favorites: number[]; owned: number[]; onFavorite: (id: number) => void; onCart: (id: number) => void }) {
  return <main><section className="home-intro"><div className="home-title-row"><div><p className="kicker">ARCHITECTURE · INTERIORS · LANDSCAPE</p><h1>Production-ready 3D models.<br/>Found in seconds.</h1></div><p>Search a million-plus professional assets, inspect the files you’ll receive, and unlock exactly what you need.</p></div><form className="hero-search" onSubmit={onSearch}><div className="search-mode">Models</div><Icon name="search" size={23}/><input value={query} onChange={e => onQuery(e.target.value)} placeholder="Try “modular sofa corona”"/><button type="button" className="image-search" disabled title="Image search is not connected in this prototype" aria-label="Image search · Demo only"><Icon name="image"/></button><button className="search-button">Search</button></form><div className="search-suggestions"><div className="quick-row"><span>Popular</span>{["Sofa", "Kitchen", "Olive tree", "Hotel lobby", "Villa"].map(term => <button key={term} onClick={() => onSearchFor(term)}>{term}</button>)}</div><div className="quick-row history-row"><span>Recent</span>{searchHistory.map(term => <button key={term} onClick={() => onSearchFor(term)}>{term}</button>)}</div></div><div className="category-rail">{[{ n: "Furniture", image: models[0].image }, { n: "Lighting", image: models[2].image }, { n: "Plants", image: models[3].image }, { n: "Kitchens", image: models[8].image }, { n: "Interior scenes", image: models[5].image }, { n: "Architecture", image: models[4].image }, { n: "Office", image: models[9].image }, { n: "Landscape", image: models[11].image }].map(item => <button key={item.n} onClick={() => onSearchFor(item.n)}><img src={item.image} alt=""/><span>{item.n}</span></button>)}</div></section>
    <ModelSection eyebrow="" title="New models" subtitle="Recently added and quality-checked." items={qualityCheckedModels.slice(0, 5)} onOpen={onOpen} favorites={favorites} owned={owned} onFavorite={onFavorite} onCart={onCart} onAll={() => onSearchFor("Newest")}/>
    <section className="collection-section"><SectionHeading eyebrow="" title="Browse by project" subtitle="Curated for real design tasks."/><div className="collection-grid">{collections.map(item => <button key={item.title} onClick={() => onSearchFor(item.title)}><img src={item.image} alt=""/><span><b>{item.title}</b><small>{item.count} models</small></span><Icon name="arrow"/></button>)}</div></section>
    <ModelSection eyebrow="" title="Popular models" subtitle="A curated demo selection." items={qualityCheckedModels.slice(5, 10)} onOpen={onOpen} favorites={favorites} owned={owned} onFavorite={onFavorite} onCart={onCart} onAll={() => onSearchFor("Popular")}/>
    <section className="free-strip"><div><span className="kicker light">TODAY’S FREE</span><h2>40 quality-checked models.<br/>Choose any 3 today.</h2><p>20 SketchUp and 20 3ds Max assets refresh daily at 00:00 UTC. Models you claim stay in My Assets.</p><button onClick={() => onNavigate("free")}>Explore today’s selection <Icon name="arrow"/></button></div><div className="free-collage">{models.filter(item => item.free).map(item => <img key={item.id} src={item.image} alt=""/>)}</div></section>
    <section className="trust-section"><div><Icon name="check" size={28}/><b>Quality checked</b><p>Only governed files receive the badge.</p></div><div><span className="trust-symbol">01</span><b>One model, one clear price</b><p>$1.99 buy once, or unlock with a plan.</p></div><div><span className="trust-symbol">∞</span><b>Keep what you unlock</b><p>Permanent access from My Assets.</p></div><div><Icon name="download" size={28}/><b>Files before hype</b><p>Real formats, versions and sizes—when verified.</p></div></section></main>;
}

function SearchResults({ query, onQuery, onSearch, type, onType, onOpen, favorites, owned, onFavorite, onCart }: { query: string; onQuery: (v: string) => void; onSearch: (e?: FormEvent) => void; type: string; onType: (v: string) => void; onOpen: (m: Model) => void; favorites: number[]; owned: number[]; onFavorite: (id: number) => void; onCart: (id: number) => void }) {
  const [paid, setPaid] = useState("All models"), [renderer, setRenderer] = useState("All renderers"), [visibleCount, setVisibleCount] = useState(40);
  const channelQueries = ["sketchup models", "3ds max models"], broadDemoQueries = ["all models", "newest", "popular", ...channelQueries, ...collections.map(item => item.title.toLowerCase())];
  const normalized = query.trim().toLowerCase(), channelEntry = channelQueries.includes(normalized), displayTitle = channelEntry ? (type === "All software" ? "All models" : `${type} models`) : query || "All models", tokens = normalized.split(/\s+/).filter(token => token.length > 2 && !["models", "model"].includes(token));
  const matchesQuery = (item: Model) => !normalized || broadDemoQueries.includes(normalized) || tokens.some(token => `${item.title} ${item.category} ${item.type} ${item.renderer || ""}`.toLowerCase().includes(token));
  const filtered = catalog.filter(item => item.checked).filter(matchesQuery).filter(item => type === "All software" || item.type === type).filter(item => paid === "All models" || (paid === "Free" ? item.free : !item.free)).filter(item => renderer === "All renderers" || item.renderer === renderer), visibleModels = filtered.slice(0, visibleCount);
  useEffect(() => setVisibleCount(40), [query, type, paid, renderer]);
  const resetFilters = () => { onQuery(""); onType("All software"); setPaid("All models"); setRenderer("All renderers"); };
  return <main className="search-page"><div className="search-workbench"><form className="workbench-input" onSubmit={onSearch}><Icon name="search" size={21}/><input value={query} onChange={e => onQuery(e.target.value)} placeholder="Search models"/><button type="button" className="workbench-image-search" disabled title="Image search · Demo only" aria-label="Image search · Demo only"><Icon name="image" size={19}/></button><button className="search-button">Search</button></form><div className="filter-bar"><FilterSelect value={type} onChange={onType} options={["All software", "SketchUp", "3ds Max"]}/><FilterSelect value={paid} onChange={setPaid} options={["All models", "Paid", "Free"]}/><FilterSelect value={renderer} onChange={setRenderer} options={["All renderers", "Corona", "V-Ray"]}/><button className="filter-reset" onClick={resetFilters}>Reset all</button></div></div><section className="results"><div className="results-head"><div><p className="kicker">PROTOTYPE CATALOG RESULTS</p><h1>{displayTitle}</h1><span>{filtered.length} matching models</span></div></div>{filtered.length ? <><div className="result-grid">{visibleModels.map(model => <ModelCard key={model.id} model={model} onOpen={onOpen} favorite={favorites.includes(model.id)} owned={owned.includes(model.id)} onFavorite={onFavorite} onCart={onCart}/>)}</div><AutoLoadMore hasMore={visibleCount < filtered.length} onLoad={() => setVisibleCount(count => Math.min(count + 20, filtered.length))}/></> : <div className="empty-state"><Icon name="search" size={38}/><h2>No matching demo models.</h2><p>Try a broader term or clear the filters.</p><button className="primary-cta" onClick={resetFilters}>Clear filters</button></div>}</section></main>;
}

function ProductDetail({ model, owned, user, favorite, onFavorite, onPrimary, onCart, onOpen, onPricing }: { model: Model; owned: boolean; user: UserMode; favorite: boolean; onFavorite: () => void; onPrimary: () => void; onCart: () => void; onOpen: (m: Model) => void; onPricing: () => void }) {
  const [activeImage, setActiveImage] = useState(0);
  const subscribed = user === "pro" || user === "max", available = model.checked;
  const sameCategory = catalog.filter(item => item.checked && item.id !== model.id && item.category === model.category), sameSoftware = catalog.filter(item => item.checked && item.id !== model.id && item.type === model.type && !sameCategory.some(relatedModel => relatedModel.id === item.id));
  const related = [...sameCategory, ...sameSoftware];
  const primaryLabel = !available ? "Temporarily unavailable" : owned ? "Download again · Demo" : model.free ? "Claim this model" : subscribed ? "Use 1 unlock" : "Buy once · $1.99";
  const stats = { polygons: (128000 + model.id * 17420).toLocaleString(), textures: String(8 + model.id * 3), components: String(4 + model.id * 2), scenes: String(1 + model.id % 4), uploaded: `2023-${String((model.id % 9) + 1).padStart(2, "0")}-${String((model.id * 3) % 27 + 1).padStart(2, "0")}` };
  const galleryViews = [{ label: "Full view", position: "center center", scale: 1 }, { label: "Detail view", position: "34% 52%", scale: 1.2 }, { label: "Side detail", position: "72% 54%", scale: 1.16 }];
  const showPrevious = () => setActiveImage(index => (index - 1 + galleryViews.length) % galleryViews.length), showNext = () => setActiveImage(index => (index + 1) % galleryViews.length);
  useEffect(() => setActiveImage(0), [model.id]);
  return <main className="pdp-page">
    <div className="breadcrumbs">Home / {model.type} Models / {model.category} / <b>{model.title}</b></div>
    <div className="pdp-main">
      <div className="pdp-gallery"><div className="thumbnail-list">{galleryViews.map((view, index) => <button key={view.label} className={activeImage === index ? "active" : ""} onClick={() => setActiveImage(index)} aria-label={`Show ${view.label}`}><img src={model.image} alt="" style={{ objectPosition: view.position, transform: `scale(${view.scale})` }}/><span>{index + 1}</span></button>)}</div><div className="main-image"><img src={model.image} alt={`${model.title} · ${galleryViews[activeImage].label}`} style={{ objectPosition: galleryViews[activeImage].position, transform: `scale(${galleryViews[activeImage].scale})` }}/><button className="gallery-arrow gallery-previous" onClick={showPrevious} aria-label="Previous image"><Icon name="arrow" size={18}/></button><button className="gallery-arrow gallery-next" onClick={showNext} aria-label="Next image"><Icon name="arrow" size={18}/></button><span className="gallery-count">{activeImage + 1} / {galleryViews.length}</span><button className={favorite ? "pdp-image-save saved" : "pdp-image-save"} onClick={onFavorite} aria-label={favorite ? "Remove from favorites" : "Save to favorites"} title={favorite ? "Saved" : "Save to favorites"}><Icon name="heart" size={20}/></button></div></div>
      <aside className="buy-panel">
        <div className="product-heading"><div><span className="software-label">{model.type}{model.version ? ` ${model.version}` : ""}</span>{model.renderer && <span className="software-label">{model.renderer}</span>}{available && <span className="quality-label" title="Quality checked" aria-label="Quality checked"><Icon name="check" size={15}/></span>}{!available && <span className="unavailable-label">Demo unavailable</span>}</div><h1>{model.title}</h1><p>By ArchZZ Studio · SKU AZ-{String(model.id).padStart(6, "0")}</p></div>
        <div className="decision-row"><div><span>BUY ONCE</span><strong>{model.free ? "FREE" : "$1.99"}</strong><small>Permanent access</small></div><div className="membership-decision"><span>{subscribed ? "YOUR PLAN" : "SUBSCRIBE"}</span>{!subscribed && <button className="membership-link" onClick={onPricing}>Get member pricing</button>}{subscribed ? <><strong>1 unlock</strong><small>{user === "max" ? "124 Max unlocks remaining" : "18 Pro unlocks remaining"}</small></> : <><b>Pro <em>≈ $0.50 / model</em></b><b>Max <em>≈ $0.33 / model</em></b></>}</div></div>
        <section className="asset-details"><h2>Asset details</h2><div className="compatibility-row"><span>FORMAT &amp; COMPATIBILITY</span><strong>{model.type}{model.version ? ` ${model.version}+` : ""}</strong><small>{model.version ? `Works with ${model.version} and newer · Earlier versions unsupported.` : "Check the listed host software before purchase."}</small></div><div className="asset-grid"><Spec label="File size" value={model.size}/><Spec label="Upload date" value={stats.uploaded}/><Spec label="Commercial use" value="Allowed"/><Spec label="Redistribution & resale" value="Not allowed"/><Spec label="Polygons" value={stats.polygons}/><Spec label="Textures" value={stats.textures}/><Spec label="Components" value={stats.components}/><Spec label="Scenes" value={stats.scenes}/></div></section>
        {owned && <div className="owned-notice"><Icon name="check"/><span><b>Already in My Assets</b><small>Demo download does not use another unlock.</small></span></div>}
        <p className="purchase-note">Prototype transaction · No real payment or file download</p>
        <div className="pdp-actions"><button className="primary-cta" onClick={onPrimary} disabled={!available}>{primaryLabel}</button>{available && !model.free && !owned && <button className="cart-cta" onClick={onCart}><Icon name="cart"/> Add to cart</button>}</div>
      </aside>
    </div>
    <ModelSection eyebrow="" title="Related models" subtitle="Similar quality-checked models." items={related} onOpen={onOpen} favorites={[]} owned={[]} onFavorite={() => {}} onCart={() => {}}/>
  </main>;
}

function FreePage({ claimed, owned, onOpen, onClaim }: { claimed: number; owned: number[]; onOpen: (m: Model) => void; onClaim: (m: Model) => void }) {
  const [tab, setTab] = useState<ModelType>("SketchUp");
  return <main className="free-page"><section className="free-hero"><div><p className="kicker light">TODAY’S FREE · REFRESHES 00:00 UTC</p><h1>Choose any 3 models today.</h1><p>20 SketchUp and 20 3ds Max models. Mix both formats however you like. Anything you claim stays in My Assets.</p></div><div className="free-counter"><span>TODAY’S ALLOWANCE</span><strong>{3 - claimed}<small>/ 3 left</small></strong><div><i style={{ width: `${(claimed / 3) * 100}%` }}/></div></div></section><div className="free-tabs"><button className={tab === "SketchUp" ? "active" : ""} onClick={() => setTab("SketchUp")}>SketchUp <span>20</span></button><button className={tab === "3ds Max" ? "active" : ""} onClick={() => setTab("3ds Max")}>3ds Max <span>20</span></button><p>Choose across both tabs · {claimed} claimed today</p></div><div className="free-grid">{todayFreeModels.filter(item => item.type === tab).map(model => <div className="free-card" key={model.id}><button className="free-image" onClick={() => onOpen(model)}><img src={model.image} alt={model.title}/><span>{model.type}</span></button><div><button onClick={() => onOpen(model)}>{model.title}</button><small>{model.category} · {model.size}</small><button className="claim-button" disabled={claimed >= 3 || owned.includes(model.id)} onClick={() => onClaim(model)}>{owned.includes(model.id) ? "In My Assets" : claimed >= 3 ? "Daily limit reached" : "Claim free"}</button></div></div>)}</div></main>;
}

function Pricing({ user, onChoose, onBrowse }: { user: UserMode; onChoose: (m: "pro" | "max") => void; onBrowse: () => void }) { return <main className="pricing-page"><section className="pricing-intro"><div><p className="kicker">PRICING</p><h1>Choose how you access models.</h1></div><p>Buy once or subscribe. Every model you unlock stays yours.</p></section><p className="pricing-demo-note">Prototype only · No real subscription or payment</p><div className="price-cards"><Plan name="Buy once" price="$1.99" suffix="per model" description="For occasional, specific model needs." features={["No subscription", "Permanent access", "Standard commercial license"]} button="Browse models" onClick={onBrowse}/><Plan name="Pro" price="$14.99" suffix="per month" description="For designers working on active projects." features={["30 model unlocks each month", "Roll over up to 60", "$0.99 extra unlocks", "Daily free models included"]} button={user === "pro" ? "Current Pro demo" : "Choose Pro"} featured={user !== "max"} onClick={() => onChoose("pro")}/><Plan name="Max" price="$49.99" suffix="per month" description="For high-volume studios and visualizers." features={["150 model unlocks each month", "Roll over up to 300", "$0.99 extra unlocks", "Daily free models included"]} button={user === "max" ? "Current Max demo" : "Choose Max"} featured={user === "max"} onClick={() => onChoose("max")}/></div><section className="pricing-rules"><h2>Clear rules, before you subscribe.</h2>{[["What happens to unlocked models?", "They remain in My Assets with permanent access."], ["Do unused unlocks roll over?", "Yes, up to 60 on Pro and 300 on Max while the plan remains active."], ["Can I buy more?", "Active subscribers can buy extra unlocks in packs of 10 for $0.99 each."], ["Can I cancel?", "Yes. Your plan remains active until the end of the paid period."]].map(([q, a]) => <details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</section></main>; }

function CartPage({ items, user, onRemove, onOpen, onCheckout }: { items: Model[]; user: UserMode; onRemove: (id: number) => void; onOpen: (m: Model) => void; onCheckout: () => void }) { const cash = items.length * 1.99, subscribed = user === "pro" || user === "max", plan = user === "max" ? "Max" : "Pro", balance = user === "max" ? 124 : 18; return <main className="cart-page"><div className="cart-title"><p className="kicker">YOUR SELECTION</p><h1>Cart <span>{items.length}</span></h1></div>{items.length === 0 ? <div className="empty-state"><Icon name="cart" size={38}/><h2>Your cart is ready for a project.</h2><p>Add paid models to compare and purchase them together.</p></div> : <div className="cart-layout"><section className="cart-items">{items.map(item => <article key={item.id}><button onClick={() => onOpen(item)}><img src={item.image} alt=""/></button><div><span>{item.type}</span><button onClick={() => onOpen(item)}>{item.title}</button><small>{item.category} · {item.size} · Standard License</small></div><strong>$1.99</strong><button className="remove" onClick={() => onRemove(item.id)}><Icon name="close"/></button></article>)}</section><aside className="order-summary"><h2>Order summary</h2><div><span>{items.length} models</span><b>${cash.toFixed(2)}</b></div>{subscribed ? <div className="recommend-box"><span>DEMO RECOMMENDATION</span><b>Use {items.length} {plan} unlocks</b><p>Prototype balance: {balance} unlocks available.</p></div> : <div className="recommend-box"><span>DEMO CHECKOUT</span><b>Buy once · ${cash.toFixed(2)}</b><p>No real payment will be initiated.</p></div>}<div className="total"><span>Demo amount due</span><strong>{subscribed ? "$0.00" : `$${cash.toFixed(2)}`}</strong></div><button className="primary-cta" onClick={onCheckout}>Review simulated checkout</button><small>Prototype only · No payment, order or file delivery</small></aside></div>}</main>; }

function Assets({ tab, onTab, owned, favorites, user, freeClaimed, onOpen, onBrowse, onPricing, onDemoDownload, onAccountNotice }: { tab: AccountTab; onTab: (tab: AccountTab) => void; owned: Model[]; favorites: Model[]; user: UserMode; freeClaimed: number; onOpen: (m: Model) => void; onBrowse: () => void; onPricing: () => void; onDemoDownload: () => void; onAccountNotice: (message: string) => void }) { const items = tab === "Favorites" ? favorites : owned; return <main className="account-page"><aside><p>ACCOUNT</p>{(["My Assets", "Plan & Unlocks", "My Orders", "Favorites", "Account Settings"] as AccountTab[]).map(item => <button key={item} className={tab === item ? "active" : ""} onClick={() => onTab(item)}>{item}</button>)}</aside><section><div className="account-head"><div><p className="kicker">ACCOUNT PROTOTYPE</p><h1>{tab}</h1></div><button className="outline-button" onClick={onBrowse}>Browse models</button></div>{tab === "Plan & Unlocks" ? <PlanUnlocks user={user} usedModels={owned.length} freeClaimed={freeClaimed} onPricing={onPricing} onCancel={() => onAccountNotice("Cancellation is not connected in this prototype")}/> : tab === "My Orders" ? owned.length ? <OrderHistory models={owned} user={user} onOpen={onOpen}/> : <AccountEmptyState icon="cart" title="No orders yet" text="Completed purchases and model unlocks will appear here with their access status." note="Prototype order history" onBrowse={onBrowse}/> : tab === "Account Settings" ? <AccountSettings onEdit={() => onAccountNotice("Profile editing is not connected in this prototype")}/> : items.length ? <div className="asset-grid">{items.map(item => <article key={item.id}><button onClick={() => onOpen(item)}><img src={item.image} alt=""/></button><span>{item.type}</span><b>{item.title}</b>{tab === "My Assets" ? <button className="download-button" onClick={onDemoDownload}><Icon name="download"/> Simulate download</button> : <button className="download-button" onClick={() => onOpen(item)}>View model</button>}</article>)}</div> : <AccountEmptyState icon={tab === "Favorites" ? "heart" : "download"} title={tab === "Favorites" ? "Save models for later" : "Your model library starts here"} text={tab === "Favorites" ? "Use the heart on any model to keep a shortlist for your next project." : "Models you buy or claim will stay here, ready to access again."} note={tab === "Favorites" ? "Your shortlist is private" : "Purchases and claimed free models appear automatically"} onBrowse={onBrowse}/>}</section></main>; }

function PlanUnlocks({ user, usedModels, freeClaimed, onPricing, onCancel }: { user: UserMode; usedModels: number; freeClaimed: number; onPricing: () => void; onCancel: () => void }) { const subscribed = user === "pro" || user === "max"; if (!subscribed) return <div className="plan-account"><section className="current-plan-card basic-plan-card"><span>CURRENT PLAN</span><div><h2>Basic</h2><button onClick={onPricing}>View Pro &amp; Max</button></div><p>Get lower per-model pricing with a Pro or Max subscription.</p></section><div className="free-credit-row"><span>TODAY’S FREE</span><b>{3 - freeClaimed} of 3 remaining</b><small>Refreshes daily at 00:00 UTC</small></div></div>; const monthly = user === "max" ? 120 : 20, rollover = user === "max" ? 30 : 10, openingUsed = user === "max" ? 26 : 12, used = Math.min(monthly + rollover, openingUsed + usedModels), remaining = monthly + rollover - used; return <div className="plan-account"><section className="current-plan-card"><span>CURRENT PLAN</span><div><h2>{user === "max" ? "Max" : "Pro"}</h2>{user === "pro" && <button onClick={onPricing}>Upgrade to Max</button>}</div><p>{user === "max" ? "$49.99 / month · 150 new credits each cycle" : "$14.99 / month · 30 new credits each cycle"}</p></section><div className="credit-summary"><div className="credit-total"><span>AVAILABLE CREDITS</span><strong>{remaining}</strong><p>of {monthly + rollover} this cycle</p></div><div><span>This month</span><b>{monthly}</b></div><div><span>Rolled over</span><b>{rollover}</b></div><div><span>Used</span><b>{used}</b></div><div><span>Remaining</span><b>{remaining}</b></div></div><div className="renewal-row"><div><span>NEXT REFRESH</span><b>September 1, 2026</b><small>{user === "max" ? "150 new credits will be added" : "30 new credits will be added"}</small></div><div><span>TODAY’S FREE</span><b>{3 - freeClaimed} of 3 remaining</b><small>Refreshes daily at 00:00 UTC</small></div></div><button className="cancel-plan" onClick={onCancel}>Cancel subscription</button></div>; }

function OrderHistory({ models, user, onOpen }: { models: Model[]; user: UserMode; onOpen: (model: Model) => void }) { return <div className="order-history"><div className="order-history-head"><span>{models.length} completed {models.length === 1 ? "record" : "records"}</span><small>Prototype records based on My Assets</small></div>{models.map((model, index) => <article key={model.id}><button className="order-model" onClick={() => onOpen(model)}><img src={model.image} alt=""/><span><b>{model.title}</b><small>{model.type}{model.renderer ? ` · ${model.renderer}` : ""}</small></span></button><div><span>ORDER</span><b>AZD-{String(model.id).padStart(6, "0")}</b></div><div><span>DATE</span><b>Aug {String(26 - index).padStart(2, "0")}, 2026</b></div><div><span>ACCESS</span><b>{model.free ? "Free claim" : user === "pro" ? "1 Pro credit" : user === "max" ? "1 Max credit" : "$1.99 buy once"}</b></div><strong className="order-status">Completed</strong></article>)}</div>; }

function AccountSettings({ onEdit }: { onEdit: () => void }) { return <div className="account-settings"><section><div className="settings-heading"><div><span>ACCOUNT INFORMATION</span><h2>Profile</h2></div></div><div className="settings-grid"><div><span>Nickname</span><b>ArchZZ Designer</b><button onClick={onEdit}>Edit nickname</button></div><div><span>Email address</span><b>designer@archzz.demo</b><small>Verified</small></div></div></section><p><Icon name="check" size={17}/> Account details shown for prototype review only.</p></div>; }

function AccountEmptyState({ icon, title, text, note, onBrowse }: { icon: "cart" | "heart" | "download"; title: string; text: string; note: string; onBrowse: () => void }) { return <div className="account-empty"><div className="account-empty-icon"><Icon name={icon} size={28}/></div><div className="account-empty-copy"><p className="kicker">NOTHING HERE YET</p><h2>{title}</h2><p>{text}</p><button className="primary-cta" onClick={onBrowse}>Browse models</button></div><p className="account-empty-note"><Icon name="check" size={17}/>{note}</p></div>; }

function AccountDemoState({ icon, title, text }: { icon: "cart" | "user"; title: string; text: string }) { return <div className="empty-state"><Icon name={icon} size={38}/><h2>{title}</h2><p>{text}</p><span className="demo-pill">Prototype only</span></div>; }

function ModelSection({ eyebrow, title, subtitle, items, onOpen, favorites, owned, onFavorite, onCart, onAll }: { eyebrow: string; title: string; subtitle: string; items: Model[]; onOpen: (m: Model) => void; favorites: number[]; owned: number[]; onFavorite: (id: number) => void; onCart: (id: number) => void; onAll?: () => void }) { const paginated = title === "Related models", [visibleCount, setVisibleCount] = useState(paginated ? 20 : items.length), visibleItems = paginated ? items.slice(0, visibleCount) : items; useEffect(() => setVisibleCount(paginated ? 20 : items.length), [paginated, items.length, items[0]?.id]); return <section className="model-section"><SectionHeading eyebrow={eyebrow} title={title} subtitle={subtitle} action={onAll}/><div className="home-model-grid">{visibleItems.map(model => <ModelCard key={model.id} model={model} onOpen={onOpen} favorite={favorites.includes(model.id)} owned={owned.includes(model.id)} onFavorite={onFavorite} onCart={onCart}/>)}</div>{paginated && <AutoLoadMore hasMore={visibleCount < items.length} onLoad={() => setVisibleCount(count => Math.min(count + 20, items.length))}/>}</section>; }
function SectionHeading({ eyebrow, title, subtitle, action }: { eyebrow: string; title: string; subtitle: string; action?: () => void }) { return <div className="section-heading"><div>{eyebrow && <p className="kicker">{eyebrow}</p>}<h2>{title}</h2>{subtitle && <span>{subtitle}</span>}</div>{action && <button onClick={action}>View all <Icon name="arrow"/></button>}</div>; }
function ModelCard({ model, onOpen, favorite, owned, onFavorite, onCart }: { model: Model; onOpen: (m: Model) => void; favorite: boolean; owned: boolean; onFavorite: (id: number) => void; onCart: (id: number) => void }) { const unavailable = !model.checked, purchasable = !owned && !model.free && !unavailable, freeAction = !owned && model.free && !unavailable, primaryAction = purchasable || freeAction, saves = 180 + model.id * 39 + (favorite ? 1 : 0); return <article className={unavailable ? "model-card unavailable" : "model-card"}><div className="model-image"><button onClick={() => onOpen(model)}><img src={model.image} alt={model.title} loading="lazy" decoding="async" sizes="(max-width: 780px) 50vw, (max-width: 1100px) 33vw, 20vw"/></button><div className="model-tags"><span>{model.type}</span>{model.renderer && <span>{model.renderer}</span>}{model.checked && <span className="quality-tag" title="Quality checked" aria-label="Quality checked"><Icon name="check" size={13}/></span>}{unavailable && <span>Demo unavailable</span>}</div></div><div className="model-copy"><button className="model-title" onClick={() => onOpen(model)}>{model.title}</button><p>{model.category} · ArchZZ Studio</p><div className="model-bottom"><strong>{unavailable ? "Unavailable" : owned ? "Owned" : model.free ? "FREE" : "$1.99"}</strong><div className="card-actions"><button className={favorite ? "save-count-button active" : "save-count-button"} onClick={() => onFavorite(model.id)} aria-label={favorite ? `Remove from favorites · ${saves} saves` : `Save to favorites · ${saves} saves`} title={favorite ? "Saved" : "Save to favorites"}><Icon name="heart" size={17}/><span>{saves}</span></button><button className={primaryAction ? "purchase-card-action" : ""} onClick={() => purchasable ? onCart(model.id) : onOpen(model)} aria-label={owned ? "Download again · Demo" : unavailable ? "View unavailable item" : model.free ? "View free model" : "Add to cart"}><Icon name={owned || model.free ? "download" : unavailable ? "arrow" : "cart"} size={18}/>{purchasable && <span>Add</span>}{freeAction && <span>Free</span>}</button></div></div></div></article>; }
function AutoLoadMore({ hasMore, onLoad }: { hasMore: boolean; onLoad: () => void }) { const marker = useRef<HTMLDivElement>(null); useEffect(() => { const node = marker.current; if (!node || !hasMore) return; const observer = new IntersectionObserver(entries => { if (entries[0]?.isIntersecting) onLoad(); }, { rootMargin: "240px 0px" }); observer.observe(node); return () => observer.disconnect(); }, [hasMore, onLoad]); return <div ref={marker} className={hasMore ? "auto-load-more" : "auto-load-more complete"} aria-live="polite"><span>{hasMore ? "Load more" : "All results shown"}</span></div>; }
function FilterSelect({ value, options, onChange, disabled }: { value: string; options: string[]; onChange?: (v: string) => void; disabled?: boolean }) { return <select value={value} onChange={e => onChange?.(e.target.value)} disabled={disabled}>{options.map(option => <option key={option}>{option}</option>)}</select>; }
function Spec({ label, value }: { label: string; value: string }) { return <div><span>{label}</span><b>{value}</b></div>; }
function Plan({ name, price, suffix, description, features, button, featured, onClick }: { name: string; price: string; suffix: string; description: string; features: string[]; button: string; featured?: boolean; onClick: () => void }) { return <article className={featured ? "price-card featured" : "price-card"}>{featured && <span className="recommended">MOST PRACTICAL</span>}<h2>{name}</h2><div className="plan-price"><strong>{price}</strong><span>{suffix}</span></div><p>{description}</p><ul>{features.map(item => <li key={item}><Icon name="check" size={16}/>{item}</li>)}</ul><button onClick={onClick}>{button}</button></article>; }
function Footer({ onNavigate, onAccount }: { onNavigate: (p: Page) => void; onAccount: (tab: AccountTab) => void }) { void onNavigate; void onAccount; return <footer className="archzz-footer"><div className="footer-main"><div><b>Company info</b><button>About ARCHZZ</button><button className="ai-studio-link">ARCHZZ AI Studio <Icon name="arrow" size={14}/></button></div><div><b>Copyright &amp; Licensing</b><button>Asset License Agreement</button><button>DMCA Policy</button></div><div><b>Help</b><button>Customer Service</button></div><div><b>Pay securely via</b><div className="payment-methods" aria-label="Visa, Mastercard, Dana, GCash, Touch 'n Go and PayPal"><span>VISA</span><span className="mastercard">●●</span><span>DANA</span><span>GCash</span><span>TNG</span><span>PayPal</span></div></div></div><div className="footer-bottom"><small>© 2026 Archzz Pte. Ltd.</small><nav aria-label="Legal"><button>Terms of Use</button><button>Privacy Policy</button><button>Cookies</button></nav></div></footer>; }
function Modal({ children, onClose }: { children: React.ReactNode; onClose: () => void }) { return <div className="modal-backdrop" role="presentation" onMouseDown={event => { if (event.currentTarget === event.target) onClose(); }}><div className="modal" role="dialog" aria-modal="true"><button className="modal-close" onClick={onClose} aria-label="Close dialog"><Icon name="close"/></button>{children}</div></div>; }
function Auth({ onContinue }: { onContinue: () => void }) { return <div className="auth-modal"><p className="kicker">CONTINUE YOUR TASK</p><h2>Sign in to save, claim or purchase models.</h2><button className="google-button" onClick={onContinue}>Continue with Google</button><div className="or"><span/>or<span/></div><label>Email address<input type="email" placeholder="you@studio.com"/></label><button className="primary-cta" onClick={onContinue}>Continue with email</button><small>We’ll return you to the same action after sign-in.</small></div>; }
function Checkout({ models, user, onPay }: { models: Model[]; user: UserMode; onPay: () => void }) { const subscribed = user === "pro" || user === "max", total = models.length * 1.99; return <div className="checkout-modal"><p className="kicker">SIMULATED CHECKOUT</p><h2>Review the prototype transaction</h2><div className="demo-notice"><b>Prototype only</b><span>No real payment, order, entitlement or download will be created.</span></div>{models.map(model => <div className="checkout-item" key={model.id}><img src={model.image} alt=""/><span><b>{model.title}</b><small>{model.type} · Demo permanent access</small></span><strong>{subscribed ? "1 unlock" : "$1.99"}</strong></div>)}<div className="checkout-lines"><span>Subtotal <b>{subscribed ? `${models.length} unlocks` : `$${total.toFixed(2)}`}</b></span><span>Tax <b>Not calculated in prototype</b></span><span className="checkout-total">Demo total <b>{subscribed ? "$0.00" : `$${total.toFixed(2)} USD`}</b></span></div>{!subscribed && <><label className="payment-option demo-payment"><input type="radio" disabled/><b>PayPal · Demo</b></label><label className="payment-option demo-payment"><input type="radio" disabled/><b>Antom · Demo</b></label></>}<button className="primary-cta" onClick={onPay}>{subscribed ? `Simulate ${models.length} unlock${models.length > 1 ? "s" : ""}` : "Complete simulated purchase"}</button><p className="legal-note">This interaction is for product review only.</p></div>; }
function Success({ model, count, onClose, onAssets }: { model: Model; count: number; onClose: () => void; onAssets: () => void }) { return <div className="success-modal"><span className="success-icon"><Icon name="check" size={34}/></span><p className="kicker">PROTOTYPE COMPLETE</p><h2>{count > 1 ? `${count} models were added to the demo assets.` : `${model.title} is now in demo My Assets.`}</h2><p>No real file download has started. Use the button below only to preview the download interaction.</p><button className="primary-cta" onClick={onClose}><Icon name="download"/> Simulate download</button><button className="text-button" onClick={onAssets}>Go to My Assets</button></div>; }
function DemoControl({ user, onUser, onReset }: { user: UserMode; onUser: (u: UserMode) => void; onReset: () => void }) { return <div className="demo-control"><span><i/> Prototype state</span><select value={user} onChange={e => onUser(e.target.value as UserMode)}><option value="guest">Guest</option><option value="basic">Registered · Basic</option><option value="pro">Pro · 18 unlocks</option><option value="max">Max · 124 unlocks</option></select><button onClick={onReset}>Reset</button></div>; }
